// Journey storybooks. Unlock prerequisites reference canonical World Experience relic IDs
// instead of duplicating mastery thresholds in the narrative layer.
export const STORY_CHAPTERS = [
  {
    id: 'story-alphabet',
    worldId: 'alphabet',
    chapter: 'Capítulo I',
    title: 'O Bosque dos Símbolos',
    emoji: '🌲',
    unlockAfterRelicId: null,
    pages: [
      { text: 'Era uma vez uma Corujinha chamada Lexia, guardiã de um bosque onde os símbolos dormiam entre folhas e livros.', emoji: '🦉' },
      { text: 'No primeiro caminho, Lexia encontrou a letra A brilhando sozinha perto de uma árvore antiga.', emoji: '🅰️' },
      { text: 'Cada nova letra tinha uma voz, uma forma e uma pista escondida em alguma palavra.', emoji: '🔤' },
      { text: 'Lexia percebeu que aprender as vinte e seis letras era como acender vinte e seis pequenas lanternas.', emoji: '✨' },
      { text: 'Quando todas as vozes despertassem, o bosque revelaria uma ponte feita de sons.', emoji: '🌉' },
    ],
  },
  {
    id: 'story-simple-syllables',
    worldId: 'syllables_basic',
    chapter: 'Capítulo II',
    title: 'As Pontes do Som',
    emoji: '🌉',
    unlockAfterRelicId: 'relic-alphabet-quill',
    pages: [
      { text: 'Com as letras despertas, Lexia ouviu dois sons se chamando de lados diferentes de um rio.', emoji: '👂' },
      { text: 'B e A se aproximaram devagar. Quando ficaram juntos, nasceu BA — uma pequena ponte de som.', emoji: '🔡' },
      { text: 'Outras letras fizeram o mesmo: MA, PA, LA e muitas combinações começaram a ligar as margens.', emoji: '🌉' },
      { text: 'Cada sílaba construída permitia atravessar para palavras que antes pareciam distantes demais.', emoji: '🪄' },
      { text: 'No fim das pontes, uma trilha mais difícil esperava por encontros de três sons.', emoji: '🧭' },
    ],
  },
  {
    id: 'story-complex-syllables',
    worldId: 'syllables_complex',
    chapter: 'Capítulo III',
    title: 'O Labirinto dos Encontros',
    emoji: '🧭',
    unlockAfterRelicId: 'relic-syllable-shell',
    pages: [
      { text: 'A nova trilha levou Lexia até um labirinto onde alguns sons só apareciam quando três caminhos se cruzavam.', emoji: '🌀' },
      { text: 'BRA surgiu atrás de uma parede de pedra. TRA apareceu quando um velho trilho começou a vibrar.', emoji: '🧱' },
      { text: 'Lexia descobriu que encontros difíceis não eram monstros: eram mapas que precisavam ser observados com calma.', emoji: '🗺️' },
      { text: 'A cada combinação compreendida, a bússola do labirinto girava menos e apontava um caminho mais claro.', emoji: '🧭' },
      { text: 'Na saída, uma enorme biblioteca aguardava por alguém capaz de transformar sons em palavras inteiras.', emoji: '📚' },
    ],
  },
  {
    id: 'story-words',
    worldId: 'words_basic',
    chapter: 'Capítulo IV',
    title: 'A Biblioteca Desperta',
    emoji: '📚',
    unlockAfterRelicId: 'relic-complex-compass',
    pages: [
      { text: 'A Biblioteca Desperta parecia silenciosa, mas cada estante guardava palavras esperando para serem chamadas pelo nome.', emoji: '📚' },
      { text: 'CASA acendeu uma janela. GATO fez surgir pegadas. MAPA abriu uma gaveta cheia de caminhos.', emoji: '🏠' },
      { text: 'Lexia percebeu que uma palavra é mais do que letras juntas: ela pode apontar para ideias, objetos e lembranças.', emoji: '💡' },
      { text: 'Quando as primeiras palavras foram reconhecidas, os livros começaram a contar pequenos pedaços de histórias.', emoji: '📖' },
      { text: 'Mas para uma história nascer de verdade, as palavras ainda precisavam aprender a caminhar lado a lado.', emoji: '🌱' },
    ],
  },
  {
    id: 'story-sentences',
    worldId: 'sentences',
    chapter: 'Capítulo V',
    title: 'O Jardim das Histórias',
    emoji: '🌱',
    unlockAfterRelicId: 'relic-word-key',
    pages: [
      { text: 'Depois da biblioteca, Lexia chegou a um jardim onde palavras soltas flutuavam como sementes ao vento.', emoji: '🌬️' },
      { text: 'Uma palavra sozinha dizia pouco. Mas quando “O”, “GATO” e “PULA” ficaram na ordem certa, uma cena inteira apareceu.', emoji: '🐱' },
      { text: 'Lexia começou a organizar palavras para formar frases, ideias e pequenas histórias com começo e sentido.', emoji: '📝' },
      { text: 'Cada frase correta fazia nascer uma nova planta, como se o jardim entendesse a força das ideias completas.', emoji: '🌿' },
      { text: 'Quando o jardim ganhou voz, uma torre distante acendeu uma luz: a jornada principal estava quase completa.', emoji: '🏮' },
    ],
  },
  {
    id: 'story-mastery',
    worldId: 'mastery',
    chapter: 'Epílogo',
    title: 'A Torre da Maestria',
    emoji: '🏮',
    unlockAfterRelicId: 'relic-sentence-seed',
    pages: [
      { text: 'Lexia subiu os degraus da Torre da Maestria levando consigo letras, sons, palavras e histórias.', emoji: '🏰' },
      { text: 'No alto da torre, ela descobriu que aprender não significa nunca mais errar.', emoji: '🌙' },
      { text: 'Aprender significa poder voltar, revisar, lembrar melhor e usar o que já sabemos para descobrir algo novo.', emoji: '🔁' },
      { text: 'A Lanterna da Maestria não marcava um fim. Ela iluminava caminhos que ainda nem tinham sido desenhados.', emoji: '🏮' },
      { text: 'E assim a primeira grande jornada de Lexia terminou do jeito certo: abrindo espaço para a próxima aventura.', emoji: '✨' },
    ],
  },
];
