// Basic syllables data for typing mode
export const BASIC_SYLLABLES = [
  { syllable: 'BA', word: 'Bala', emoji: '🍬' },
  { syllable: 'BE', word: 'Bebê', emoji: '👶' },
  { syllable: 'BI', word: 'Bico', emoji: '🐦' },
  { syllable: 'BO', word: 'Bolo', emoji: '🎂' },
  { syllable: 'BU', word: 'Burro', emoji: '🫏' },
  { syllable: 'CA', word: 'Cama', emoji: '🛏️' },
  { syllable: 'CE', word: 'Cena', emoji: '🎭' },
  { syllable: 'CI', word: 'Cinco', emoji: '5️⃣' },
  { syllable: 'CO', word: 'Copo', emoji: '🥤' },
  { syllable: 'CU', word: 'Cubo', emoji: '🎲' },
  { syllable: 'DA', word: 'Dado', emoji: '🎲' },
  { syllable: 'DE', word: 'Dedo', emoji: '👆' },
  { syllable: 'DI', word: 'Dica', emoji: '💡' },
  { syllable: 'DO', word: 'Dono', emoji: '🏠' },
  { syllable: 'FA', word: 'Faca', emoji: '🔪' },
  { syllable: 'FE', word: 'Feno', emoji: '🌾' },
  { syllable: 'FI', word: 'Fita', emoji: '🎀' },
  { syllable: 'FO', word: 'Foca', emoji: '🦭' },
  { syllable: 'GA', word: 'Gato', emoji: '🐱' },
  { syllable: 'GE', word: 'Gelo', emoji: '🧊' },
  { syllable: 'LA', word: 'Lama', emoji: '🌊' },
  { syllable: 'LE', word: 'Leão', emoji: '🦁' },
  { syllable: 'LI', word: 'Lima', emoji: '🍋' },
  { syllable: 'LO', word: 'Lobo', emoji: '🐺' },
  { syllable: 'LU', word: 'Lua', emoji: '🌙' },
  { syllable: 'MA', word: 'Mala', emoji: '🧳' },
  { syllable: 'ME', word: 'Medo', emoji: '😱' },
  { syllable: 'MI', word: 'Mico', emoji: '🐒' },
  { syllable: 'MO', word: 'Moto', emoji: '🏍️' },
  { syllable: 'MU', word: 'Mula', emoji: '🫏' },
  { syllable: 'NA', word: 'Nada', emoji: '🏊' },
  { syllable: 'NE', word: 'Neto', emoji: '👦' },
  { syllable: 'NI', word: 'Ninho', emoji: '🐣' },
  { syllable: 'NO', word: 'Nó', emoji: '🪢' },
  { syllable: 'PA', word: 'Pato', emoji: '🦆' },
  { syllable: 'PE', word: 'Pera', emoji: '🍐' },
  { syllable: 'PI', word: 'Pipa', emoji: '🪁' },
  { syllable: 'PO', word: 'Povo', emoji: '👥' },
  { syllable: 'PU', word: 'Pulga', emoji: '🦟' },
  { syllable: 'SA', word: 'Sapo', emoji: '🐸' },
  { syllable: 'SE', word: 'Seta', emoji: '➡️' },
  { syllable: 'SI', word: 'Sino', emoji: '🔔' },
  { syllable: 'SO', word: 'Sopa', emoji: '🍲' },
  { syllable: 'SU', word: 'Sumo', emoji: '🧃' },
  { syllable: 'TA', word: 'Tatu', emoji: '🐾' },
  { syllable: 'TE', word: 'Tela', emoji: '🖥️' },
  { syllable: 'TI', word: 'Tio', emoji: '👨' },
  { syllable: 'TO', word: 'Toco', emoji: '🌳' },
  { syllable: 'TU', word: 'Tubo', emoji: '🔧' },
  { syllable: 'VA', word: 'Vaca', emoji: '🐄' },
  { syllable: 'VE', word: 'Vela', emoji: '🕯️' },
  { syllable: 'VI', word: 'Vida', emoji: '🌱' },
  { syllable: 'VO', word: 'Voto', emoji: '🗳️' },
];

export const BASIC_WORDS = [
  { word: 'BOLA', emoji: '⚽', hint: 'usada para jogar' },
  { word: 'CASA', emoji: '🏠', hint: 'onde moramos' },
  { word: 'GATO', emoji: '🐱', hint: 'animal que mia' },
  { word: 'PATO', emoji: '🦆', hint: 'animal que nada' },
  { word: 'SAPO', emoji: '🐸', hint: 'pula e coaxa' },
  { word: 'MAPA', emoji: '🗺️', hint: 'mostra lugares' },
  { word: 'FADA', emoji: '🧚', hint: 'tem varinha mágica' },
  { word: 'LUPA', emoji: '🔍', hint: 'aumenta as coisas' },
  { word: 'MALA', emoji: '🧳', hint: 'carrega roupas' },
  { word: 'PIPA', emoji: '🪁', hint: 'voa no vento' },
  { word: 'BOCA', emoji: '👄', hint: 'para falar e comer' },
  { word: 'DEDO', emoji: '👆', hint: 'parte da mão' },
  { word: 'FOGO', emoji: '🔥', hint: 'quente e laranja' },
  { word: 'MEDO', emoji: '😱', hint: 'quando temos susto' },
  { word: 'NIDO', emoji: '🐣', hint: 'onde as aves vivem' },
  { word: 'RATO', emoji: '🐭', hint: 'pequeno e bigodudo' },
  { word: 'SINO', emoji: '🔔', hint: 'faz bim-bom' },
  { word: 'TELA', emoji: '🖥️', hint: 'onde você assiste' },
  { word: 'UVAS', emoji: '🍇', hint: 'fruta roxa' },
  { word: 'VACA', emoji: '🐄', hint: 'animal do leite' },
];